Investigate python-debian compatibility ...
I'm half expecting this build to fail on Python 3.5 due to the recent
publication of python-debian release 0.1.34 (on January 17, 2019):

  Traceback (most recent call last):
    File "$VIRTUAL_ENV/lib/python3.5/site-packages/py2deb/cli.py", line 200, in main
      archives, relationships = converter.convert(arguments)
    File "$VIRTUAL_ENV/lib/python3.5/site-packages/py2deb/converter.py", line 752, in convert
      archive = package.convert()
    File "$VIRTUAL_ENV/lib/python3.5/site-packages/py2deb/package.py", line 502, in convert
      copy_files=False)
    File "$VIRTUAL_ENV/lib/python3.5/site-packages/deb_pkg_tools/package.py", line 638, in build_package
      package_file = os.path.join(repository, determine_package_archive(directory))
    File "$VIRTUAL_ENV/lib/python3.5/site-packages/deb_pkg_tools/package.py", line 753, in determine_package_archive
      architecture = fields.get('Architecture', '').strip()
  AttributeError: 'Deb822' object has no attribute 'get'

Let's see if the test suite correctly reproduces this issue...