Bug fix: Swallow unpickling errors instead of propagating them
In general I am very much opposed to Python code that swallows
exceptions when it doesn't know how to handle them, because it can
inadvertently obscure an issue's root cause and/or exacerbate the
issue.

But caching deserves an exception. Any code that exists solely as an
optimization should not raise exceptions caused by the caching logic.
This should avoid the following traceback which I just ran into:

Traceback (most recent call last):
  File ".../lib/python2.7/site-packages/deb_pkg_tools/cli.py", line 382, in with_repository_wrapper
    with_repository(directory, *command, cache=cache)
  File ".../lib/python2.7/site-packages/deb_pkg_tools/repo.py", line 366, in with_repository
    cache=kw.get('cache'))
  File ".../lib/python2.7/site-packages/deb_pkg_tools/repo.py", line 228, in update_repository
    cache=cache)
  File ".../lib/python2.7/site-packages/deb_pkg_tools/repo.py", line 91, in scan_packages
    fields = dict(inspect_package_fields(archive, cache=cache))
  File ".../lib/python2.7/site-packages/deb_pkg_tools/package.py", line 480, in inspect_package_fields
    value = entry.get_value()
  File ".../lib/python2.7/site-packages/deb_pkg_tools/cache.py", line 268, in get_value
    from_fs = pickle.load(handle)
ValueError: unsupported pickle protocol: 3